### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 't') on extension activation

### ISSUE THREAD

**Issue by JuniorLoch** [seatonjiang/gitmoji-vscode#42]
### This is the log that I got from vscode extension host
![image](https://user-images.githubusercontent.com/72585178/205320164-2fd58c5d-53e2-4ea4-8b93-457dbda449e6.png)

### I went to where it broke in my local files but I have no idea what could be done to help, somehow `vscode.l10n` is undefined
![image](https://user-images.githubusercontent.com/72585178/205321126-beccc54e-7c50-401f-a2d7-405b22e3d5ac.png)

**Comment by ayumu-1212** [comment]
same thing happened to me

**Comment by seatonjiang** [comment]
Hi @ayumu-1212 @JuniorLoch 

I probably found the problem because VSCODE is 1.73.1 in my test environment, and https://github.com/microsoft/vscode-l10n states that it needs to be at least 1.73.0.If the version is lower than 1.73.0, please update the VSCode version and try if the problem still occurs?

![image](https://user-images.githubusercontent.com/57834639/205412519-bcc0ff34-88ac-4264-8c42-7eddd58d4d72.png)

**Comment by ayumu-1212** [comment]
Hi @seatonjiang cc: @JuniorLoch 
I update the VSCode version from 1.63.2 to 1.73.1, so this problem is solved.
Thank you so much for your advise.

**Comment by JuniorLoch** [comment]
HI @ayumu-1212, @seatonjiang 
Updated the vscode version too, and it worked again, thank you guys.
