### ISSUE TITLE
Gitmoji no longer working: Emojis are not put into commit message

### ISSUE THREAD

**Issue by dbachran** [seatonjiang/gitmoji-vscode#46]
Haven't been using VS Code for a few weeks now (holidays and such), but I just noticed that Gitmoji does no longer insert any emojis into the commit message anymore. I am able to select the desired emoji, but when I click on it, nothing happens.

I am using VS Code both natively (with Windows Git repos) and in WSL. Gitmoji seems to be enabled (haven't changed anything here) and was working fine earlier in my setup.

Visual Studio Code

Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z (1 wk ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19042
Sandboxed: No

**Comment by seatonjiang** [comment]
Hi @dbachran 

We use the same version of the configuration, but I use everything fine without finding problems. When you have a problem there, there is feedback on the plugin page (there is an error reported when there is a problem), check to see if there is feedback?

**Comment by E1337Kat** [comment]
Just to check, because I had the same issue, and it turned out to be a non-issue, but in the extension host output, when trying to select an emoji, does it print out an error like 
```
2023-01-17 15:51:22.730 [error] TypeError: Cannot read properties of undefined (reading 'path')
    at /~/.vscode/extensions/vtrois.gitmoji-vscode-1.0.9/out/extension.js:48:73
    at Array.find (<anonymous>)
    at /~/.vscode/extensions/vtrois.gitmoji-vscode-1.0.9/out/extension.js:47:63
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
It seems that the original extension I used by this vtrois person does not exist anymore and when looking up the extension this was the first hit and seemingly the same thing (but with newer updates even).

The fix was simple, disable/uninstall the old extension and install this extension such that your extensions are like this: 
![image](https://user-images.githubusercontent.com/2062516/213214055-41a69b56-02b2-42dd-ab8c-0708615f8780.png)


I guess the extension I used before was either a copy of this one and I didn't realize it, or this is a fork and the last person left VS code or something?? I dunno. it's just a bit weird.
